import { Header } from "@/layouts";
import "./globals.css";
import { Inter } from "next/font/google";
import Particles from "@/components/particles";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lak Saeid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="overflow-hidden" lang="en">
      <body className={"bg-primary " + inter.className}>
        <div className="mx-auto max-w-7xl text-white h-full">
        <Header />
          {children}
          </div>
        <Particles/>
      </body>
    </html>
  );
}
