import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lak Saeid",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-screen w-screen" lang="en">
      <body className={"bg-primary w-screen h-screen " + inter.className}>
        <div className="mx-auto max-w-7xl text-white h-full">{children}</div>
      </body>
    </html>
  );
}
